apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-descriptor
  name: ai-descriptor
  namespace: gamebase
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ai-descriptor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/transparent-proxy: "true"
        consul.hashicorp.com/transparent-proxy-overwrite-upstream-port: "8080"
      labels:
        app: ai-descriptor
    spec:
      serviceAccountName: ai-descriptor
      containers:
        - image: ghcr.io/emil476m/gamebase-ad:0.0.37
          imagePullPolicy: IfNotPresent
          name: gamebase-ad
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: CONSUL_ACL
              valueFrom:
                secretKeyRef:
                  name: consul-acl
                  key: token
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ai-descriptor
  namespace: gamebase
spec:
  selector:
    app: ai-descriptor
  ports:
    - port: 5000
      targetPort: 8080
      name: http