apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: create-service
  name: create-service
  namespace: gamebase
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: create-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
      labels:
        app: create-service
    spec:
      serviceAccountName: create-service
      containers:
        - image: ghcr.io/emil476m/gamebase-cs:0.0.37
          imagePullPolicy: IfNotPresent
          name: gamebase-cs
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: pgconn
              valueFrom:
                secretKeyRef:
                  name: gamebase-db-secret
                  key: pgconn
            - name: CONSUL_ACL
              valueFrom:
                secretKeyRef:
                  name: consul-acl
                  key: token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: create-service
  namespace: gamebase
spec:
  selector:
    app: create-service
  ports:
    - port: 6000
      targetPort: 6000
      name: http