apiVersion: v1
kind: Namespace
metadata:
  name: featurehub
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: featurehub-h2-data
  namespace: featurehub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: featurehub
  namespace: featurehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featurehub
  template:
    metadata:
      labels:
        app: featurehub
    spec:
      containers:
        - name: featurehub
          image: featurehub/party-server:latest
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: featurehub-h2-data
              mountPath: /db
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: featurehub-h2-data
          persistentVolumeClaim:
            claimName: featurehub-h2-data
---
apiVersion: v1
kind: Service
metadata:
  name: featurehub
  namespace: featurehub
spec:
  selector:
    app: featurehub
  ports:
    - port: 4085         # External port
      targetPort: 8085   # Container port
      protocol: TCP
      nodePort: 30085    # NodePort (must be 30000â€“32767)
  type: NodePort
