apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-handler
  name: review-handler
  namespace: gamebase
  annotations:
    consul.hashicorp.com/connect-inject: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: review-handler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: review-handler
    spec:
      serviceAccountName: review-handler
      containers:
        - image: ghcr.io/emil476m/gamebase-rh:0.0.37
          imagePullPolicy: IfNotPresent
          name: gamebase-rh
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:  
            - name: CONSUL_ACL
              valueFrom:
                secretKeyRef:
                  name: consul-acl
                  key: token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: review-handler
  namespace: gamebase
  annotations:
    consul.hashicorp.com/connect-inject: "true"
spec:
  selector:
    app: review-handler
  ports:
    - port: 7080
      targetPort: 7080
      name: http