apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: gamebase
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-frontend
  namespace: gamebase
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-handler
  namespace: gamebase
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: search-engine
  namespace: gamebase
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-descriptor
  namespace: gamebase
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-service
  namespace: gamebase