apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-frontend
  name: web-frontend
  namespace: gamebase
  annotations:
    consul.hashicorp.com/connect-inject: "true"
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      serviceAccountName: web-frontend
      containers:
        - image: ghcr.io/emil476m/gamebase-web:0.0.37
          imagePullPolicy: IfNotPresent
          name: gamebase-web
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: CONSUL_ACL
              valueFrom:
                secretKeyRef:
                  name: consul-acl
                  key: token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: gamebase
  annotations:
    consul.hashicorp.com/connect-inject: "true"
spec:
  selector:
    app: web-frontend
  ports:
    - port: 4200
      targetPort: 4200
      name: http