server:
  annotations:
      consul.hashicorp.com/connect-inject: "false"
  
  podAnnotations:
      consul.hashicorp.com/connect-inject: "false"
  image:
    tag: "1.21.1"
  serviceAccount:
     create: true
  affinity: ""
  ha:
    enabled: true
    raft: 
      enabled: true
      setNodeId: true
      config: |
          ui = true
           storage "raft" {
              path    = "/vault/data/"
            }

            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = "true"

            }
            service_registration "kubernetes" {}
injector:
  enabled: false